// for (let i = 1; i <= 5; i++) {
//   console.log(Aman);
// }

// let i = 1;
// do {
//   console.log("Aman");
//   i++;
// } while (i <= 10);

// let i = 1;
// while (i <= 10) {
//   console.log("babbar");
//   i++;
// }

// for (let i = 1; i <= 5; i++) {
//   console.log(i);
// }

// let i = 1;
// while (i < 6) {
//   console.log(i);
//   i++;
// }

// reverse counting

// for (let i = 5; i > 0; i--) {
//   console.log(i);
// }

// for (let i = 1; i <= 6; i++) {
//   if (i == 4) {
//     break;
//   } else {
//     console.log(i);
//   }
// }

// for (let i = 1; i <= 6; i++) {
//   if (i == 4) {
//     continue;
//   } else {
//     console.log(i);
//   }
//}
